services:
  db:
    image: mysql
    container_name: cinemadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=marlon
      - MYSQL_DATABASE=cinema
  backend:
    image: "python:3.11.1"
    container_name: cinema-backend
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=marlon
      - MYSQL_DATABASE=cinema
      # Podemos poner el nombre del servidor o el nombre del contenedor
      - MYSQL_HOSTNAME=cinemadb
      - MYSQL_PORT=3306
    command: sh -c "sleep 5s && python ./src/index.py"
    depends_on:
      - db
    # Links tambien se puede reemplazar con "network", no es necesario con mongodb (verificar)
    links:
      - db